name: carpooling_beta
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-138.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_native_splash: ^2.2.8
  introduction_screen: ^3.0.2
  flutter_svg: ^1.1.0
  intl: ^0.17.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.0.10
  # flutter_google_places: ^0.3.0
  flutter_google_places_hoc081098: ^1.1.0
  dio: ^4.0.0
  http: ^0.13.4
  flutter_speed_dial: ^6.0.0
  flutter_advanced_drawer: ^1.3.2
  # location: ^4.4.0
  stream_chat_flutter: ^4.4.0
  google_sign_in: ^5.4.1
  html: ^0.15.0
  pandabar: ^0.1.2
  flutter_secure_storage: ^5.1.2
  firebase_messaging: ^12.0.1
  cloud_firestore: ^3.4.1
  firebase_core: ^1.20.0
  firebase_auth: ^3.5.1
  rxdart: ^0.27.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

  flutter: 
    sdk: flutter

dev_dependencies: 
  lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_launcher_icons: "^0.10.0"
  flutter_test: 
    sdk: flutter
  
flutter: 
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "poolero"
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#EBE9FF"
  image: assets/logo.png
  fullscreen: true
  android: true
  ios: true
