// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpCuz_MRksCi_Qr96vboZafpj6hzjauXM',
    appId: '1:632890754562:web:ce3f657a6769a811f2c91b',
    messagingSenderId: '632890754562',
    projectId: 'carpooling-fc3b4',
    authDomain: 'carpooling-fc3b4.firebaseapp.com',
    databaseURL: 'https://carpooling-fc3b4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carpooling-fc3b4.appspot.com',
    measurementId: 'G-7PCMH1XWW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyKxpWybZ2aDhVlgeB7RWbFgzcL05bO3M',
    appId: '1:632890754562:android:6f42ea6fa874d521f2c91b',
    messagingSenderId: '632890754562',
    projectId: 'carpooling-fc3b4',
    databaseURL: 'https://carpooling-fc3b4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carpooling-fc3b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8g6TfJTypgP0k27iZDpd-A6j-49fxGDA',
    appId: '1:632890754562:ios:145912a21dbaa2adf2c91b',
    messagingSenderId: '632890754562',
    projectId: 'carpooling-fc3b4',
    databaseURL: 'https://carpooling-fc3b4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carpooling-fc3b4.appspot.com',
    androidClientId: '632890754562-lgno5tjmt44u8s9hj4os850dsgrdnjre.apps.googleusercontent.com',
    iosClientId: '632890754562-koib0ulkodrfbbc0754hf6o8b55qgbn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.carpooingBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8g6TfJTypgP0k27iZDpd-A6j-49fxGDA',
    appId: '1:632890754562:ios:145912a21dbaa2adf2c91b',
    messagingSenderId: '632890754562',
    projectId: 'carpooling-fc3b4',
    databaseURL: 'https://carpooling-fc3b4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carpooling-fc3b4.appspot.com',
    androidClientId: '632890754562-lgno5tjmt44u8s9hj4os850dsgrdnjre.apps.googleusercontent.com',
    iosClientId: '632890754562-koib0ulkodrfbbc0754hf6o8b55qgbn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.carpooingBeta',
  );
}
